### ISSUE TITLE
main is red at 801b7a0d (#404): four failures in components/landing/

### ISSUE THREAD

**Issue by cyrusobiz-coder** [dkmobilewash/prova#440]
`main` is failing CI. Every branch rebased onto it inherits the failures, which read as the branch's own.

## Evidence

- `gh run list --branch main --workflow ci.yml`: `801b7a0d` (#404) = **failure**; `1aea765e` (#430, the commit before it) = success.
- Reproduced locally in a clean worktree checked out at `origin/main` with a fresh `pnpm install --frozen-lockfile`: `3 failed | 6253 passed (6256)`, `2 failed | 385 passed (387)` test files, and `typecheck` exit 2.

## The four failures, all in #404's new `components/landing/` and its rewrite of `app/page.tsx`

**1. typecheck (exit 2)**

```
components/landing/PayApplicationPanel.tsx(106,5): error TS2353:
Object literal may only specify known properties,
and 'retainagePercent' does not exist in type 'PayAppSummaryInput'.
```

CI runs Test → Lint → Typecheck → Build, and Test fails first, so on CI this error is not even reached — Lint, Typecheck and Build all report `skipped`. It only shows up if you run `pnpm typecheck` directly.

**2 & 3. `lib/hoursRenderCensus.test.ts`**

`components/landing/ApprenticeRatioPanel.tsx` renders four bare hours values:

```
:153  {day.journeymanHours}
:153  {day.apprenticeHours}
:154  {day.allowedApprenticeHours}
:156  {day.unclassifiedHours}
```

and `components/landing/panelChrome.tsx` holds a second copy of the display rounding.

**4. `lib/pageWidthCensus.test.ts`**

> `apps/web/app/page.tsx` no longer sets its own width. Delete it from `UNCONVERTED_PAGES` and drop the count by one — the list only shrinks.

#404 made the fix and left the entry on the ratchet.

## On the fix

Two of these are censuses catching new code exactly as designed. The landing page is a marketing mockup, so the hours are demo figures — **`NOT_AN_HOURS_NUMBER` with a reason may well be the right answer rather than wrapping them in `formatHours()`**. That is a judgement for #404's author, which is why this is an issue rather than a PR. #4's `pageWidthCensus` entry is unambiguous: delete the line and drop the count.

## Worth a separate look: how it merged

A red `main` means CI passed on some earlier SHA of #404 and not on the one that landed. That is CLAUDE.md's #59 scar from the other direction — the checks were not lying, they were answering about a commit nobody asked them about. Worth checking whether the merge path reads the colour rather than the head SHA.
