### ISSUE TITLE
main is RED on typecheck since #404 — landing panel passes a field #409 removed

### ISSUE THREAD

**Issue by cyrusobiz-coder** [dkmobilewash/prova#438]
`origin/main` at `801b7a0d` **fails `pnpm typecheck`**, on a clean checkout with no local changes:

```
apps/web/components/landing/PayApplicationPanel.tsx(106,5): error TS2353:
Object literal may only specify known properties, and 'retainagePercent'
does not exist in type 'PayAppSummaryInput'.
```

Verified by stashing everything and running against `801b7a0d` directly — exit code 2, this is the only error.

## What happened

- **#409** (`0c4f3747`) removed `retainagePercent` from `PayAppSummaryInput`, deliberately and correctly — it was supplied by every caller and read by nothing, and the type now carries a comment saying so.
- **#404** (`801b7a0d`, merged last) added `apps/web/components/landing/PayApplicationPanel.tsx`, which passes `retainagePercent: RETAINAGE_PERCENT` at line 106.

#404 branched before that removal, was green on its own base, and merged without re-running against the main it was landing on. Neither PR was wrong on its own; the pair is.

This is the scar CLAUDE.md already records, arriving from a new direction: **a PR's checks are green about the base they ran against, not the base it merges into.** "The PR says green" is not "main is green".

## The fix

One line. The argument is read by nothing — `calculatePayAppSummary` never mentions it, which is exactly why #409 removed it — so deleting line 106 of `PayApplicationPanel.tsx` restores the build with no behaviour change. The panel is static marketing content.

Not doing it myself: `components/landing/` is #404's lane and I do not want to hide a main-is-red event inside an unrelated test PR. Happy to send the one-liner if whoever owns #404 would rather not context-switch — say the word.

## Why this is urgent rather than tidy

`ci.yml` runs typecheck, so **every open PR's CI is red on this**, through no fault of the PR. That is the expensive part: a red check that belongs to somebody else trains people to read past red, and this repo has already paid for an absent check being read as a passing one.

**Comment by cyrusobiz-coder** [comment]
**Correction and expansion: `main` is red on `test` as well as `typecheck`, and `test` fails first.**

The original report named only the typecheck error. That was incomplete — `ci.yml` runs test → lint → typecheck → build, so **Test fails first and Lint/Typecheck/Build are `skipped`**. Anyone reading a failed run will see the test failures and never reach the TS2353 above.

Verified on a **detached checkout of clean `origin/main` at `801b7a0d`**, nothing local in the tree:

```
× page width census > holds nothing on the allowance list that no longer needs allowing
  → apps/web/app/page.tsx no longer sets its own width. Delete it from
    UNCONVERTED_PAGES and drop the count by one — the list only shrinks.

× every rendered hours figure goes through lib/render-hours.ts > has no bare render
× there is exactly one implementation of the hours format > has no second copy of the arithmetic
```

So the full picture is **four failures, all traceable to #404 landing on a main that had moved**:

| Check | Failure | Cause |
| --- | --- | --- |
| `test` | `pageWidthCensus` stale entry | #404 converted `app/page.tsx`; its entry in `UNCONVERTED_PAGES` is now stale |
| `test` | `hoursRenderCensus` ×2 | a bare hours render reached `main` |
| `typecheck` | TS2353 `retainagePercent` | #409 removed the field, #404 passes it |

**The `pageWidthCensus` one is worth calling out as a success, not just a failure.** That is a shrink-only allowance list doing exactly what it is for: #404 *fixed* `app/page.tsx`, and the census refuses to stay green while its list still claims the page is unconverted. The fix is to delete the line and lower the count — which is the check working, and it is the same ratchet shape #423 is adding to the numeric census.

None of these are hard. They are the cost of merging a PR whose CI was green about an older base.
